[package]
name = "rcore-fs-sefs"
version = "0.1.0"
authors = ["WangRunji <wangrunji0408@163.com>"]
edition = "2021"

[dependencies]
rcore-fs = { path = "../rcore-fs", features = ["no_std"] }
static_assertions = "0.3"
spin = "0.5"
log = "=0.4.20"
uuid = { version = "1.6", default-features = false, features = ["v4"] }
bitvec = { version = "0.17", default-features = false, features = ["alloc"] }
bitflags = "2.3"

[features]
std = ["rcore-fs/std"]
# Enable this feture when this crate is used for creating an SEFS image
# (e.g., sefs-cli). When this feature is enabled, the MAC of an SEFS inode
# will be updated when the inode is closed. When this feature is disabled,
# the MAC of an SEFS inode will be checked when the inode is open.
create_image = []
