[package]
name = "rcore-fs-unionfs"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "=0.4.20"
rcore-fs = { path = "../rcore-fs" }
rcore-fs-tstd-lock = { path = "../rcore-fs-tstd-lock", optional = true }
spin = { version = "0.5", optional = true }

[dev-dependencies]
rcore-fs-ramfs = { path = "../rcore-fs-ramfs" }

[features]
create_image = ["spin", "rcore-fs/std"]
no_std = ["rcore-fs-tstd-lock", "rcore-fs/no_std"]
